[theme]
primaryColor = "#4A86E8"  # Subdued Blue
backgroundColor = "#0E1117"
secondaryBackgroundColor = "#262730"
textColor = "#FAFAFA"
font = "sans serif"
[server]
maxUploadSize = 200
enableCORS = false
enableXsrfProtection = false
